// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: count.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Protocol {
  public static partial class CountService
  {
    static readonly string __ServiceName = "protocol.CountService";

    static readonly grpc::Marshaller<global::Protocol.IncrRequest> __Marshaller_protocol_IncrRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protocol.IncrRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Protocol.IncrResponse> __Marshaller_protocol_IncrResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Protocol.IncrResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Protocol.IncrRequest, global::Protocol.IncrResponse> __Method_Incr = new grpc::Method<global::Protocol.IncrRequest, global::Protocol.IncrResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Incr",
        __Marshaller_protocol_IncrRequest,
        __Marshaller_protocol_IncrResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Protocol.CountReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CountService</summary>
    public abstract partial class CountServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Protocol.IncrResponse> Incr(global::Protocol.IncrRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CountService</summary>
    public partial class CountServiceClient : grpc::ClientBase<CountServiceClient>
    {
      /// <summary>Creates a new client for CountService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CountServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CountService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CountServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CountServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CountServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Protocol.IncrResponse Incr(global::Protocol.IncrRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Incr(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Protocol.IncrResponse Incr(global::Protocol.IncrRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Incr, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Protocol.IncrResponse> IncrAsync(global::Protocol.IncrRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return IncrAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Protocol.IncrResponse> IncrAsync(global::Protocol.IncrRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Incr, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CountServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CountServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CountServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Incr, serviceImpl.Incr).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CountServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Incr, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Protocol.IncrRequest, global::Protocol.IncrResponse>(serviceImpl.Incr));
    }

  }
}
#endregion
